apiVersion: apps/v1
kind: Deployment
metadata:
  name: lunite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lunite
  template:
    metadata:
      labels:
        app: lunite
    spec:
      containers:
        - name: lunite
          image: gcr.io/cs144-25s-kimberlyyu-458421/lunite:$GITHUB_SHA
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lunite-service
spec:
  type: LoadBalancer
  selector:
    app: lunite
  ports:
    - port: 80
      targetPort: 80
