name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: cs144-25s-kimberlyyu-458421

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint || echo "Linting skipped or warnings present"

    - name: Build app
      run: npm run build

    - name: Build Docker image
      run: docker build -t gcr.io/cs144-25s-kimberlyyu-458421/lunite:$GITHUB_SHA .

    - name: Push Docker image
      run: docker push gcr.io/cs144-25s-kimberlyyu-458421/lunite:$GITHUB_SHA

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials lunite-cluster --region=us-west1

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl set image deployment/lunite lunite=gcr.io/cs144-25s-kimberlyyu-458421/lunite:$GITHUB_SHA
