name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: cs144-25s-kimberlyyu-458421

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker us-west1-docker.pkg.dev

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint || echo "Linting skipped or warnings present"

    - name: Build app
      run: npm run build

    - name: Build Docker image
      run: docker build -t us-west1-docker.pkg.dev/cs144-25s-kimberlyyu-458421/lunite/lunite:$GITHUB_SHA .

    - name: Push Docker image to Artifact Registry
      run: docker push us-west1-docker.pkg.dev/cs144-25s-kimberlyyu-458421/lunite/lunite:$GITHUB_SHA

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials lunite-cluster --region=us-west1

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl set image deployment/lunite lunite=us-west1-docker.pkg.dev/cs144-25s-kimberlyyu-458421/lunite/lunite:$GITHUB_SHA
